x = int(input("Input your first number.: "))
y = int(input("Input your second number.: "))
print(f"{x} plus {y} is {x + y}.")
print(f"{x} minus {y} is {x - y}.")
print(f"{x} times {y} is {x * y}.")
print(f"{x} divided by {y} is {x / y}.")
print(f"{x} to the power of {y} is {x ** y}.")
print(f"The remainder of {x} divided by {y} is {x % y}.")
print(f"The quotient of {x} divided by {y} is {x // y}.")
